#include "SPCategories.h"


std::map<int, std::string> SPCategories::catMap;
SPCategories::SPCategories()
{
}


SPCategories::~SPCategories()
{
}

bool SPCategories::GetAreaName(int Category, std::string & Area, std::string & Product)
{
	EnsureMap();
	std::map<int, std::string>::iterator it = SPCategories::catMap.find(Category);
	if (it != SPCategories::catMap.end())
	{
		std::size_t pos = it->second.find("|");
		Area = it->second.substr(0, pos);
		Product = it->second.substr(pos + 1);
		return true;
	}
	Area = "<Unknow>";
	char* hex = new char[100];
    sprintf_s(hex, 100, "<unknown>(0x%x)", Category);
	Product = hex;
	delete[] hex;

	return false;
}

bool SPCategories::ContainsAreaName(int Category, std::string PartialName)
{
	EnsureMap();
	std::map<int, std::string>::iterator it = SPCategories::catMap.begin();
	while (it != SPCategories::catMap.end())
	{
		if (it->second.find(PartialName) != std::string::npos)
			return true;
		it++;
	}
	return false;
}

std::map<int,int> SPCategories::GetListAreaName(std::string PartialName)
{
	auto list = std::map<int, int>();

	EnsureMap();
	std::map<int, std::string>::iterator it = SPCategories::catMap.begin();
	while (it != SPCategories::catMap.end())
	{
		if (it->second.find(PartialName) != std::string::npos)
			list[it->first]=1;
		it++;
	}
	return list;
}


std::string SPCategories::GetSevLevel(int SevId)
{
	switch ((ULSTraceLevel)SevId)
	{
	case ULSTraceLevel::None:
		return "None";
		break;
	case ULSTraceLevel::Unexpected:
		return "Unexpected";
		break;
	case ULSTraceLevel::Monitorable:
		return "Monitorable";
		break;
	case ULSTraceLevel::High:
		return "High";
		break;
	case ULSTraceLevel::Medium:
		return "Medium";
		break;
	case ULSTraceLevel::Verbose:
		return "Verbose";
		break;
	case ULSTraceLevel::VerboseEx:
		return "VerboseEx";
		break;
	default:
		return "*InvalidLevel*";

	}
	return "";
}

/* Got from this PowerShell script

Add-PSSnapin Microsoft.SharePoint.Powershell -ErrorAction SilentlyContinue
$logLevels = (Get-SPLogLevel | Sort Id)

$lines = New-Object 'System.Collections.Generic.List[string]';
foreach($level in $logLevels)
{
$lines.Add("`tSPCategories::catMap[0x$($level.Id.ToString(""x"))]=""$($level.Area)|$($level.Name.Replace(""|"", "":""))"";");
Write-Host "`tSPCategories::catMap[0x$($level.Id.ToString(""x"))]=""$($level.Area)|$($level.Name.Replace(""|"", "":""))"";";
}

$lines | Out-File spcat.txt

*/
void SPCategories::EnsureMap()
{
	if (SPCategories::catMap.size() == 0)
	{
		SPCategories::catMap[0x10001] = "SPO Diagnostics|Augmentation";
		SPCategories::catMap[0x10002] = "SPO Diagnostics|Claims";
		SPCategories::catMap[0x10003] = "SPO Diagnostics|Directory";
		SPCategories::catMap[0x10004] = "SPO Diagnostics|Resolving";
		SPCategories::catMap[0x10005] = "SPO Diagnostics|Searching";
		SPCategories::catMap[0x10006] = "SPO Diagnostics|Spods";
		SPCategories::catMap[0x10007] = "SPO Diagnostics|Group ID Migration";
		SPCategories::catMap[0x10008] = "SPO Diagnostics|Utility";
		SPCategories::catMap[0x10009] = "SPO Diagnostics|RPS Cookie";
		SPCategories::catMap[0x1000a] = "SPO Diagnostics|RPS Idcrl";
		SPCategories::catMap[0x1000b] = "SPO Diagnostics|RPS Infrastructure";
		SPCategories::catMap[0x1000c] = "SPO Diagnostics|RPS Membership Provider";
		SPCategories::catMap[0x1000d] = "SPO Diagnostics|RPS Sign-In";
		SPCategories::catMap[0x1000e] = "SPO Diagnostics|Rps Sign In As A Different User";
		SPCategories::catMap[0x1000f] = "SPO Diagnostics|RPS Sign-Out";
		SPCategories::catMap[0x10010] = "SPO Diagnostics|RPS Ticket";
		SPCategories::catMap[0x10011] = "SPO Diagnostics|SPO Token";
		SPCategories::catMap[0x10012] = "SPO Diagnostics|SPO Sign-In";
		SPCategories::catMap[0x10013] = "SPO Diagnostics|SPO Sign-Out";
		SPCategories::catMap[0x10014] = "SPO Diagnostics|SPO Invitation";
		SPCategories::catMap[0x10015] = "SPO Diagnostics|SPO Authentication Policy";
		SPCategories::catMap[0x10016] = "SPO Diagnostics|SPO Landing";
		SPCategories::catMap[0x10017] = "SPO Diagnostics|Share By Email";
		SPCategories::catMap[0x10018] = "SPO Diagnostics|Self Service Create";
		SPCategories::catMap[0x10019] = "SPO Diagnostics|Roaming Applications";
		SPCategories::catMap[0x1001a] = "SPO Diagnostics|DSI Roaming Mru";
		SPCategories::catMap[0x1001b] = "SPO Diagnostics|User Diagnostics";
		SPCategories::catMap[0x1001c] = "SPO Diagnostics|Flighting";
		SPCategories::catMap[0x1001d] = "SPO Diagnostics|Task";
		SPCategories::catMap[0x1001e] = "SPO Diagnostics|MultiGeo";
		SPCategories::catMap[0x1001f] = "SPO Diagnostics|TenantDivestiture";
		SPCategories::catMap[0x10020] = "SPO Diagnostics|Monitor Debug";
		SPCategories::catMap[0x10021] = "SPO Diagnostics|Monitor Failure";
		SPCategories::catMap[0x10022] = "SPO Diagnostics|ReliabilityMonitoring";
		SPCategories::catMap[0x10023] = "SPO Diagnostics|Tenant Workflow";
		SPCategories::catMap[0x10024] = "SPO Diagnostics|Tenant Site Provisioning";
		SPCategories::catMap[0x10025] = "SPO Diagnostics|Tenant OM";
		SPCategories::catMap[0x10026] = "SPO Diagnostics|Tenant Web Service";
		SPCategories::catMap[0x10027] = "SPO Diagnostics|SiteCreationProvider";
		SPCategories::catMap[0x10028] = "SPO Diagnostics|Site Provisioning Provider";
		SPCategories::catMap[0x10029] = "SPO Diagnostics|RealTimeMonitoringProvider";
		SPCategories::catMap[0x1002a] = "SPO Diagnostics|SyncToAD TimerJob";
		SPCategories::catMap[0x1002b] = "SPO Diagnostics|Sync Library";
		SPCategories::catMap[0x1002c] = "SPO Diagnostics|Prv Generic Task";
		SPCategories::catMap[0x1002d] = "SPO Diagnostics|Prv AD Helper Task";
		SPCategories::catMap[0x1002e] = "SPO Diagnostics|Prv Control Task";
		SPCategories::catMap[0x1002f] = "SPO Diagnostics|Prv Tenant Task";
		SPCategories::catMap[0x10030] = "SPO Diagnostics|Prv UserTask";
		SPCategories::catMap[0x10031] = "SPO Diagnostics|FailoverWebService";
		SPCategories::catMap[0x10032] = "SPO Diagnostics|AkamaiDNSFailoverService";
		SPCategories::catMap[0x119001] = "Web Content Management|Publishing Cache";
		SPCategories::catMap[0x119002] = "Web Content Management|Content Deployment";
		SPCategories::catMap[0x119003] = "Web Content Management|Microsoft Content Management Server 2002 Migration";
		SPCategories::catMap[0x119004] = "Web Content Management|Publishing Provisioning";
		SPCategories::catMap[0x119005] = "Web Content Management|Publishing";
		SPCategories::catMap[0x119006] = "Web Content Management|Site Management";
		SPCategories::catMap[0x119007] = "Web Content Management|Asset Library";
		SPCategories::catMap[0x119008] = "Web Content Management|CMIS Connectors";
		SPCategories::catMap[0x137d001] = "Office Automation Services|WAC Hosting Interaction";
		SPCategories::catMap[0x137d002] = "Office Automation Services|WAC Persisted Cache Storage";
		SPCategories::catMap[0x137d003] = "Office Automation Services|Office Viewing Architecture";
		SPCategories::catMap[0x137d004] = "Office Automation Services|Office Web Apps common";
		SPCategories::catMap[0x137d005] = "Office Automation Services|Sample Service";
		SPCategories::catMap[0x137d006] = "Office Automation Services|Sample Watchdog";
		SPCategories::catMap[0x137d007] = "Office Automation Services|Load Balancer";
		SPCategories::catMap[0x137d008] = "Office Automation Services|OneNote Web App Merge Module";
		SPCategories::catMap[0x137d009] = "Office Automation Services|OneNote Web App Search";
		SPCategories::catMap[0x137d00a] = "Office Automation Services|OneNote Web App Storage";
		SPCategories::catMap[0x137d00b] = "Office Automation Services|Word Web App Viewer";
		SPCategories::catMap[0x137d00c] = "Office Automation Services|Office Web Apps Shared";
		SPCategories::catMap[0x137d00d] = "Office Automation Services|Office Web Apps Exceptions";
		SPCategories::catMap[0x137d00e] = "Office Automation Services|Word Web App File Open";
		SPCategories::catMap[0x137d00f] = "Office Automation Services|Word Web App File Save";
		SPCategories::catMap[0x137d010] = "Office Automation Services|Word Web App Initialization";
		SPCategories::catMap[0x137d011] = "Office Automation Services|Word Web App Rendering";
		SPCategories::catMap[0x137d012] = "Office Automation Services|Word Web App File Conversion";
		SPCategories::catMap[0x137d013] = "Office Automation Services|Proofing";
		SPCategories::catMap[0x137d014] = "Office Automation Services|PowerPoint";
		SPCategories::catMap[0x137d015] = "Office Automation Services|PowerPoint Front End";
		SPCategories::catMap[0x137d016] = "Office Automation Services|PowerPoint Web Services";
		SPCategories::catMap[0x137d017] = "Office Automation Services|PowerPoint initialization";
		SPCategories::catMap[0x137d018] = "Office Automation Services|PowerPoint document";
		SPCategories::catMap[0x137d019] = "Office Automation Services|PowerPoint slide load";
		SPCategories::catMap[0x137d01a] = "Office Automation Services|PowerPoint render";
		SPCategories::catMap[0x137d01b] = "Office Automation Services|PowerPoint file manager";
		SPCategories::catMap[0x137d01c] = "Office Automation Services|PowerPoint editing";
		SPCategories::catMap[0x137d01d] = "Office Automation Services|PowerPoint viewer";
		SPCategories::catMap[0x137d01e] = "Office Automation Services|PowerPoint static";
		SPCategories::catMap[0x137d01f] = "Office Automation Services|PowerPoint administration";
		SPCategories::catMap[0x137d020] = "Office Automation Services|PowerPoint Mobile Viewer";
		SPCategories::catMap[0x137d021] = "Office Automation Services|Word Mobile Viewer";
		SPCategories::catMap[0x137d022] = "Office Automation Services|Web Service throttling";
		SPCategories::catMap[0x137d023] = "Office Automation Services|Office Web Apps Cell Storage";
		SPCategories::catMap[0x137d024] = "Office Automation Services|Sandbox Host";
		SPCategories::catMap[0x137d025] = "Office Automation Services|Browser SQM";
		SPCategories::catMap[0x137d026] = "Office Automation Services|Service Test Host Web";
		SPCategories::catMap[0x137d027] = "Office Automation Services|Service Test Host Wshi";
		SPCategories::catMap[0x137d028] = "Office Automation Services|Cell Storage Library";
		SPCategories::catMap[0x137d029] = "Office Automation Services|Cell Storage Technical Details";
		SPCategories::catMap[0x137d02a] = "Office Automation Services|Cell Storage Log File Output";
		SPCategories::catMap[0x137d02b] = "Office Automation Services|Word Web App Commenting";
		SPCategories::catMap[0x137d02c] = "Office Automation Services|Mobile WAC infrastructure";
		SPCategories::catMap[0x137d02d] = "Office Automation Services|End-to-end Office Performance";
		SPCategories::catMap[0x137d02e] = "Office Automation Services|SQM QoS Service";
		SPCategories::catMap[0x137d02f] = "Office Automation Services|SQM QoS Service Watchdog";
		SPCategories::catMap[0x137d030] = "Office Automation Services|Broadcast";
		SPCategories::catMap[0x137d031] = "Office Automation Services|Broadcast Web Services";
		SPCategories::catMap[0x137d032] = "Office Automation Services|Broadcast Backend";
		SPCategories::catMap[0x137d033] = "Office Automation Services|Broadcast UI";
		SPCategories::catMap[0x137d034] = "Office Automation Services|Broadcast Services";
		SPCategories::catMap[0x137d035] = "Office Automation Services|Broadcast Health Monitoring";
		SPCategories::catMap[0x137d036] = "Office Automation Services|Office Foundation Classes";
		SPCategories::catMap[0x137d037] = "Office Automation Services|Page Statistics";
		SPCategories::catMap[0x137d038] = "Office Automation Services|Security Context";
		SPCategories::catMap[0x137d039] = "Office Automation Services|Office Web Apps Editors Table";
		SPCategories::catMap[0x137d03a] = "Office Automation Services|Word Web App File Locking";
		SPCategories::catMap[0x137d03b] = "Office Automation Services|Word Web App Coauthoring";
		SPCategories::catMap[0x137d03c] = "Office Automation Services|Word Web App Exiting";
		SPCategories::catMap[0x137d03d] = "Office Automation Services|Word Web App Common";
		SPCategories::catMap[0x137d03e] = "Office Automation Services|Word Web App Merge";
		SPCategories::catMap[0x137d03f] = "Office Automation Services|Mobile Redirection";
		SPCategories::catMap[0x137d040] = "Office Automation Services|Visio Application";
		SPCategories::catMap[0x137d041] = "Office Automation Services|Visio Application Boot Sequence";
		SPCategories::catMap[0x137d042] = "Office Automation Services|Visio Front End Web Service";
		SPCategories::catMap[0x137d043] = "Office Automation Services|Visio Service";
		SPCategories::catMap[0x137d044] = "Office Automation Services|Visio Document";
		SPCategories::catMap[0x137d045] = "Office Automation Services|Visio User Management";
		SPCategories::catMap[0x137d046] = "Office Automation Services|Visio File Store";
		SPCategories::catMap[0x1c41001] = "SharePoint Server Search|Administration";
		SPCategories::catMap[0x1c41001] = "SharePoint Foundation Search|Administration";
		SPCategories::catMap[0x1c41004] = "SharePoint Foundation Search|Backup";
		SPCategories::catMap[0x1c41004] = "SharePoint Server Search|Backup";
		SPCategories::catMap[0x1c41005] = "SharePoint Server Search|CB Common";
		SPCategories::catMap[0x1c41005] = "SharePoint Foundation Search|CB Common";
		SPCategories::catMap[0x1c4101b] = "SharePoint Server Search|DSSLogin";
		SPCategories::catMap[0x1c4101b] = "SharePoint Foundation Search|DSSLogin";
		SPCategories::catMap[0x1c4101f] = "SharePoint Server Search|EventLog";
		SPCategories::catMap[0x1c4101f] = "SharePoint Foundation Search|EventLog";
		SPCategories::catMap[0x1c41020] = "SharePoint Server Search|FeatureExtractorPlugin";
		SPCategories::catMap[0x1c41020] = "SharePoint Foundation Search|FeatureExtractorPlugin";
		SPCategories::catMap[0x1c41021] = "SharePoint Server Search|Search Featurization";
		SPCategories::catMap[0x1c41021] = "SharePoint Foundation Search|Search Featurization";
		SPCategories::catMap[0x1c41023] = "SharePoint Foundation Search|FTE";
		SPCategories::catMap[0x1c41023] = "SharePoint Server Search|FTE";
		SPCategories::catMap[0x1c41032] = "SharePoint Server Search|IDXPIChunkBuffer";
		SPCategories::catMap[0x1c41032] = "SharePoint Foundation Search|IDXPIChunkBuffer";
		SPCategories::catMap[0x1c41033] = "SharePoint Foundation Search|IDXPIDestruction";
		SPCategories::catMap[0x1c41033] = "SharePoint Server Search|IDXPIDestruction";
		SPCategories::catMap[0x1c41034] = "SharePoint Foundation Search|IDXPIEventLog";
		SPCategories::catMap[0x1c41034] = "SharePoint Server Search|IDXPIEventLog";
		SPCategories::catMap[0x1c41035] = "SharePoint Server Search|IDXPIFTECursor";
		SPCategories::catMap[0x1c41035] = "SharePoint Foundation Search|IDXPIFTECursor";
		SPCategories::catMap[0x1c41036] = "SharePoint Foundation Search|IDXPIGlobalObjectManager";
		SPCategories::catMap[0x1c41036] = "SharePoint Server Search|IDXPIGlobalObjectManager";
		SPCategories::catMap[0x1c41037] = "SharePoint Server Search|IDXPIPerfCntr";
		SPCategories::catMap[0x1c41037] = "SharePoint Foundation Search|IDXPIPerfCntr";
		SPCategories::catMap[0x1c41038] = "SharePoint Server Search|IDXPIPlugin";
		SPCategories::catMap[0x1c41038] = "SharePoint Foundation Search|IDXPIPlugin";
		SPCategories::catMap[0x1c41039] = "SharePoint Foundation Search|IDXPIPropMapper";
		SPCategories::catMap[0x1c41039] = "SharePoint Server Search|IDXPIPropMapper";
		SPCategories::catMap[0x1c4103a] = "SharePoint Server Search|IDXPIUpgrade";
		SPCategories::catMap[0x1c4103a] = "SharePoint Foundation Search|IDXPIUpgrade";
		SPCategories::catMap[0x1c4103b] = "SharePoint Server Search|IDXPIWords";
		SPCategories::catMap[0x1c4103b] = "SharePoint Foundation Search|IDXPIWords";
		SPCategories::catMap[0x1c41046] = "SharePoint Server Search|PerfCounter Common";
		SPCategories::catMap[0x1c41046] = "SharePoint Foundation Search|PerfCounter Common";
		SPCategories::catMap[0x1c41047] = "SharePoint Foundation Search|FaultInjection";
		SPCategories::catMap[0x1c41047] = "SharePoint Server Search|FaultInjection";
		SPCategories::catMap[0x1c4104b] = "SharePoint Foundation Search|Query";
		SPCategories::catMap[0x1c4104b] = "SharePoint Server Search|Query";
		SPCategories::catMap[0x1c4104c] = "SharePoint Foundation Search|Query Processor (advanced)";
		SPCategories::catMap[0x1c4104c] = "SharePoint Server Search|Query Processor (advanced)";
		SPCategories::catMap[0x1c4104d] = "SharePoint Foundation Search|FTEAdmin";
		SPCategories::catMap[0x1c4104d] = "SharePoint Server Search|FTEAdmin";
		SPCategories::catMap[0x1c4104e] = "SharePoint Foundation Search|FDComponentSelection";
		SPCategories::catMap[0x1c4104e] = "SharePoint Server Search|FDComponentSelection";
		SPCategories::catMap[0x1c4104f] = "SharePoint Foundation Search|Exceptions";
		SPCategories::catMap[0x1c4104f] = "SharePoint Server Search|Exceptions";
		SPCategories::catMap[0x1c41050] = "SharePoint Foundation Search|FTEFiles";
		SPCategories::catMap[0x1c41050] = "SharePoint Server Search|FTEFiles";
		SPCategories::catMap[0x1c41051] = "SharePoint Foundation Search|FDFilter";
		SPCategories::catMap[0x1c41051] = "SharePoint Server Search|FDFilter";
		SPCategories::catMap[0x1c41052] = "SharePoint Server Search|FTEIndexingMaps";
		SPCategories::catMap[0x1c41052] = "SharePoint Foundation Search|FTEIndexingMaps";
		SPCategories::catMap[0x1c41053] = "SharePoint Foundation Search|FDNoiseWords";
		SPCategories::catMap[0x1c41053] = "SharePoint Server Search|FDNoiseWords";
		SPCategories::catMap[0x1c41054] = "SharePoint Foundation Search|FDProtocolHandlerInternal";
		SPCategories::catMap[0x1c41054] = "SharePoint Server Search|FDProtocolHandlerInternal";
		SPCategories::catMap[0x1c41055] = "SharePoint Foundation Search|FDProtocolHandlerOutput";
		SPCategories::catMap[0x1c41055] = "SharePoint Server Search|FDProtocolHandlerOutput";
		SPCategories::catMap[0x1c41056] = "SharePoint Foundation Search|FTEQuery";
		SPCategories::catMap[0x1c41056] = "SharePoint Server Search|FTEQuery";
		SPCategories::catMap[0x1c41057] = "SharePoint Server Search|QueryComponentSelection";
		SPCategories::catMap[0x1c41057] = "SharePoint Foundation Search|QueryComponentSelection";
		SPCategories::catMap[0x1c41058] = "SharePoint Foundation Search|QueryNoise";
		SPCategories::catMap[0x1c41058] = "SharePoint Server Search|QueryNoise";
		SPCategories::catMap[0x1c41059] = "SharePoint Foundation Search|Query Processor";
		SPCategories::catMap[0x1c41059] = "SharePoint Server Search|Query Processor";
		SPCategories::catMap[0x1c4105a] = "SharePoint Foundation Search|QueryRange";
		SPCategories::catMap[0x1c4105a] = "SharePoint Server Search|QueryRange";
		SPCategories::catMap[0x1c4105b] = "SharePoint Foundation Search|QueryRank";
		SPCategories::catMap[0x1c4105b] = "SharePoint Server Search|QueryRank";
		SPCategories::catMap[0x1c4105c] = "SharePoint Foundation Search|QueryThesaurus";
		SPCategories::catMap[0x1c4105c] = "SharePoint Server Search|QueryThesaurus";
		SPCategories::catMap[0x1c4105d] = "SharePoint Foundation Search|QueryWords";
		SPCategories::catMap[0x1c4105d] = "SharePoint Server Search|QueryWords";
		SPCategories::catMap[0x1c4105e] = "SharePoint Foundation Search|FDWordSink";
		SPCategories::catMap[0x1c4105e] = "SharePoint Server Search|FDWordSink";
		SPCategories::catMap[0x1c4105f] = "SharePoint Foundation Search|RichErrorReporting";
		SPCategories::catMap[0x1c4105f] = "SharePoint Server Search|RichErrorReporting";
		SPCategories::catMap[0x1c41062] = "SharePoint Server Search|ScopesCompilation";
		SPCategories::catMap[0x1c41062] = "SharePoint Foundation Search|ScopesCompilation";
		SPCategories::catMap[0x1c41063] = "SharePoint Foundation Search|ScopesPlugin";
		SPCategories::catMap[0x1c41063] = "SharePoint Server Search|ScopesPlugin";
		SPCategories::catMap[0x1c41064] = "SharePoint Server Search|ScopesQuery";
		SPCategories::catMap[0x1c41064] = "SharePoint Foundation Search|ScopesQuery";
		SPCategories::catMap[0x1c41069] = "SharePoint Foundation Search|Advanced Tracing";
		SPCategories::catMap[0x1c41069] = "SharePoint Server Search|Advanced Tracing";
		SPCategories::catMap[0x1c4106b] = "SharePoint Foundation Search|Tripoli BigTable";
		SPCategories::catMap[0x1c4106b] = "SharePoint Server Search|Tripoli BigTable";
		SPCategories::catMap[0x1c4106c] = "SharePoint Server Search|Tripoli BitStm";
		SPCategories::catMap[0x1c4106c] = "SharePoint Foundation Search|Tripoli BitStm";
		SPCategories::catMap[0x1c4106d] = "SharePoint Server Search|Tripoli Cat";
		SPCategories::catMap[0x1c4106d] = "SharePoint Foundation Search|Tripoli Cat";
		SPCategories::catMap[0x1c4106e] = "SharePoint Server Search|Tripoli Content Index";
		SPCategories::catMap[0x1c4106e] = "SharePoint Foundation Search|Tripoli Content Index";
		SPCategories::catMap[0x1c4106f] = "SharePoint Foundation Search|Tripoli CU";
		SPCategories::catMap[0x1c4106f] = "SharePoint Server Search|Tripoli CU";
		SPCategories::catMap[0x1c41070] = "SharePoint Server Search|Tripoli Cursor";
		SPCategories::catMap[0x1c41070] = "SharePoint Foundation Search|Tripoli Cursor";
		SPCategories::catMap[0x1c41071] = "SharePoint Server Search|Tripoli DocSum";
		SPCategories::catMap[0x1c41071] = "SharePoint Foundation Search|Tripoli DocSum";
		SPCategories::catMap[0x1c41072] = "SharePoint Foundation Search|Tripoli Exceptions";
		SPCategories::catMap[0x1c41072] = "SharePoint Server Search|Tripoli Exceptions";
		SPCategories::catMap[0x1c41073] = "SharePoint Server Search|Tripoli Falloc";
		SPCategories::catMap[0x1c41073] = "SharePoint Foundation Search|Tripoli Falloc";
		SPCategories::catMap[0x1c41074] = "SharePoint Server Search|Tripoli Filter";
		SPCategories::catMap[0x1c41074] = "SharePoint Foundation Search|Tripoli Filter";
		SPCategories::catMap[0x1c41075] = "SharePoint Server Search|Tripoli Filter Registration";
		SPCategories::catMap[0x1c41075] = "SharePoint Foundation Search|Tripoli Filter Registration";
		SPCategories::catMap[0x1c41076] = "SharePoint Server Search|Tripoli FilterWids";
		SPCategories::catMap[0x1c41076] = "SharePoint Foundation Search|Tripoli FilterWids";
		SPCategories::catMap[0x1c41077] = "SharePoint Foundation Search|Tripoli FindFirst";
		SPCategories::catMap[0x1c41077] = "SharePoint Server Search|Tripoli FindFirst";
		SPCategories::catMap[0x1c41079] = "SharePoint Foundation Search|Tripoli Fresh List";
		SPCategories::catMap[0x1c41079] = "SharePoint Server Search|Tripoli Fresh List";
		SPCategories::catMap[0x1c4107a] = "SharePoint Server Search|Tripoli FSNotify";
		SPCategories::catMap[0x1c4107a] = "SharePoint Foundation Search|Tripoli FSNotify";
		SPCategories::catMap[0x1c4107b] = "SharePoint Foundation Search|Tripoli Heap";
		SPCategories::catMap[0x1c4107b] = "SharePoint Server Search|Tripoli Heap";
		SPCategories::catMap[0x1c4107d] = "SharePoint Server Search|Tripoli Key Maker";
		SPCategories::catMap[0x1c4107d] = "SharePoint Foundation Search|Tripoli Key Maker";
		SPCategories::catMap[0x1c4107e] = "SharePoint Foundation Search|Tripoli KeyList";
		SPCategories::catMap[0x1c4107e] = "SharePoint Server Search|Tripoli KeyList";
		SPCategories::catMap[0x1c4107f] = "SharePoint Server Search|Tripoli MergeLog";
		SPCategories::catMap[0x1c4107f] = "SharePoint Foundation Search|Tripoli MergeLog";
		SPCategories::catMap[0x1c41080] = "SharePoint Server Search|Tripoli Noise";
		SPCategories::catMap[0x1c41080] = "SharePoint Foundation Search|Tripoli Noise";
		SPCategories::catMap[0x1c41081] = "SharePoint Server Search|Tripoli Normalize";
		SPCategories::catMap[0x1c41081] = "SharePoint Foundation Search|Tripoli Normalize";
		SPCategories::catMap[0x1c41082] = "SharePoint Server Search|Tripoli Parse";
		SPCategories::catMap[0x1c41082] = "SharePoint Foundation Search|Tripoli Parse";
		SPCategories::catMap[0x1c41083] = "SharePoint Server Search|Tripoli PComp";
		SPCategories::catMap[0x1c41083] = "SharePoint Foundation Search|Tripoli PComp";
		SPCategories::catMap[0x1c41084] = "SharePoint Server Search|Tripoli PDir";
		SPCategories::catMap[0x1c41084] = "SharePoint Foundation Search|Tripoli PDir";
		SPCategories::catMap[0x1c41085] = "SharePoint Foundation Search|Tripoli Pending";
		SPCategories::catMap[0x1c41085] = "SharePoint Server Search|Tripoli Pending";
		SPCategories::catMap[0x1c41086] = "SharePoint Foundation Search|Tripoli Perf";
		SPCategories::catMap[0x1c41086] = "SharePoint Server Search|Tripoli Perf";
		SPCategories::catMap[0x1c41087] = "SharePoint Server Search|Tripoli PidTable";
		SPCategories::catMap[0x1c41087] = "SharePoint Foundation Search|Tripoli PidTable";
		SPCategories::catMap[0x1c41088] = "SharePoint Server Search|Tripoli PropStore";
		SPCategories::catMap[0x1c41088] = "SharePoint Foundation Search|Tripoli PropStore";
		SPCategories::catMap[0x1c41089] = "SharePoint Foundation Search|Tripoli PropTime";
		SPCategories::catMap[0x1c41089] = "SharePoint Server Search|Tripoli PropTime";
		SPCategories::catMap[0x1c4108a] = "SharePoint Foundation Search|Tripoli Proxy";
		SPCategories::catMap[0x1c4108a] = "SharePoint Server Search|Tripoli Proxy";
		SPCategories::catMap[0x1c4108b] = "SharePoint Foundation Search|Tripoli Query";
		SPCategories::catMap[0x1c4108b] = "SharePoint Server Search|Tripoli Query";
		SPCategories::catMap[0x1c4108c] = "SharePoint Foundation Search|Tripoli QUtil";
		SPCategories::catMap[0x1c4108c] = "SharePoint Server Search|Tripoli QUtil";
		SPCategories::catMap[0x1c4108d] = "SharePoint Server Search|Tripoli Range Query";
		SPCategories::catMap[0x1c4108d] = "SharePoint Foundation Search|Tripoli Range Query";
		SPCategories::catMap[0x1c4108e] = "SharePoint Server Search|Tripoli Regex";
		SPCategories::catMap[0x1c4108e] = "SharePoint Foundation Search|Tripoli Regex";
		SPCategories::catMap[0x1c4108f] = "SharePoint Server Search|Tripoli Results";
		SPCategories::catMap[0x1c4108f] = "SharePoint Foundation Search|Tripoli Results";
		SPCategories::catMap[0x1c41090] = "SharePoint Server Search|Tripoli RowTime";
		SPCategories::catMap[0x1c41090] = "SharePoint Foundation Search|Tripoli RowTime";
		SPCategories::catMap[0x1c41091] = "SharePoint Server Search|Tripoli SecStore";
		SPCategories::catMap[0x1c41091] = "SharePoint Foundation Search|Tripoli SecStore";
		SPCategories::catMap[0x1c41092] = "SharePoint Server Search|Tripoli Srch";
		SPCategories::catMap[0x1c41092] = "SharePoint Foundation Search|Tripoli Srch";
		SPCategories::catMap[0x1c41093] = "SharePoint Server Search|Tripoli Thesaurus";
		SPCategories::catMap[0x1c41093] = "SharePoint Foundation Search|Tripoli Thesaurus";
		SPCategories::catMap[0x1c41095] = "SharePoint Foundation Search|Tripoli VA";
		SPCategories::catMap[0x1c41095] = "SharePoint Server Search|Tripoli VA";
		SPCategories::catMap[0x1c41096] = "SharePoint Server Search|Tripoli WidList";
		SPCategories::catMap[0x1c41096] = "SharePoint Foundation Search|Tripoli WidList";
		SPCategories::catMap[0x1c41097] = "SharePoint Foundation Search|Tripoli Words";
		SPCategories::catMap[0x1c41097] = "SharePoint Server Search|Tripoli Words";
		SPCategories::catMap[0x1c41098] = "SharePoint Foundation Search|Tripoli Workids";
		SPCategories::catMap[0x1c41098] = "SharePoint Server Search|Tripoli Workids";
		SPCategories::catMap[0x1c41099] = "SharePoint Foundation Search|Tripoli YACC";
		SPCategories::catMap[0x1c41099] = "SharePoint Server Search|Tripoli YACC";
		SPCategories::catMap[0x1c4109a] = "SharePoint Foundation Search|TripoliBufferCache";
		SPCategories::catMap[0x1c4109a] = "SharePoint Server Search|TripoliBufferCache";
		SPCategories::catMap[0x1c4109b] = "SharePoint Server Search|Used Component";
		SPCategories::catMap[0x1c4109b] = "SharePoint Foundation Search|Used Component";
		SPCategories::catMap[0x1c410ad] = "SharePoint Foundation Search|Search service events";
		SPCategories::catMap[0x1c410ad] = "SharePoint Server Search|Search service events";
		SPCategories::catMap[0x1c410af] = "SharePoint Foundation Search|Content Index Server";
		SPCategories::catMap[0x1c410af] = "SharePoint Server Search|Content Index Server";
		SPCategories::catMap[0x1c410b2] = "SharePoint Server Search|Query Processor Events";
		SPCategories::catMap[0x1c410b2] = "SharePoint Foundation Search|Query Processor Events";
		SPCategories::catMap[0x1c410ba] = "SharePoint Server Search|IndexerTimeTraces";
		SPCategories::catMap[0x1c410ba] = "SharePoint Foundation Search|IndexerTimeTraces";
		SPCategories::catMap[0x1c410c5] = "SharePoint Server Search|HealthRule";
		SPCategories::catMap[0x1c410c5] = "SharePoint Foundation Search|HealthRule";
		SPCategories::catMap[0x1c410c6] = "SharePoint Foundation Search|Admin Audit";
		SPCategories::catMap[0x1c410c6] = "SharePoint Server Search|Admin Audit";
		SPCategories::catMap[0x1c410c8] = "SharePoint Server Search|Analytics";
		SPCategories::catMap[0x1c410c8] = "SharePoint Foundation Search|Analytics";
		SPCategories::catMap[0x1c410cb] = "SharePoint Foundation Search|Search foundation common task";
		SPCategories::catMap[0x1c410cb] = "SharePoint Server Search|Search foundation common task";
		SPCategories::catMap[0x1c410d0] = "SharePoint Foundation Search|App Model";
		SPCategories::catMap[0x1c410d0] = "SharePoint Server Search|App Model";
		SPCategories::catMap[0x1c410d4] = "SharePoint Server Search|QueryCache";
		SPCategories::catMap[0x1c410d4] = "SharePoint Foundation Search|QueryCache";
		SPCategories::catMap[0x1c410d8] = "SharePoint Server Search|Query Throttling";
		SPCategories::catMap[0x1c410d8] = "SharePoint Foundation Search|Query Throttling";
		SPCategories::catMap[0x1c410da] = "SharePoint Foundation Search|Exchange Integration";
		SPCategories::catMap[0x1c410da] = "SharePoint Server Search|Exchange Integration";
		SPCategories::catMap[0x1c410db] = "SharePoint Foundation Search|Discovery";
		SPCategories::catMap[0x1c410db] = "SharePoint Server Search|Discovery";
		SPCategories::catMap[0x1c410dc] = "SharePoint Foundation Search|Tenant Graph Api";
		SPCategories::catMap[0x1c410dc] = "SharePoint Server Search|Tenant Graph Api";
		SPCategories::catMap[0x1c414b1] = "SharePoint Server Search|Crawler:Common";
		SPCategories::catMap[0x1c414b1] = "SharePoint Foundation Search|Crawler:Common";
		SPCategories::catMap[0x1c414b2] = "SharePoint Foundation Search|Crawler:Gatherer Plugin";
		SPCategories::catMap[0x1c414b2] = "SharePoint Server Search|Crawler:Gatherer Plugin";
		SPCategories::catMap[0x1c414b3] = "SharePoint Foundation Search|Crawler:Gatherer Service";
		SPCategories::catMap[0x1c414b3] = "SharePoint Server Search|Crawler:Gatherer Service";
		SPCategories::catMap[0x1c414b4] = "SharePoint Server Search|Crawler:Content Plugin";
		SPCategories::catMap[0x1c414b4] = "SharePoint Foundation Search|Crawler:Content Plugin";
		SPCategories::catMap[0x1c414b5] = "SharePoint Server Search|Crawler:FilterDaemon";
		SPCategories::catMap[0x1c414b5] = "SharePoint Foundation Search|Crawler:FilterDaemon";
		SPCategories::catMap[0x1c414b6] = "SharePoint Foundation Search|Crawler:Azure Plugin";
		SPCategories::catMap[0x1c414b6] = "SharePoint Server Search|Crawler:Azure Plugin";
		SPCategories::catMap[0x1c41515] = "SharePoint Server Search|Connectors:File";
		SPCategories::catMap[0x1c41515] = "SharePoint Foundation Search|Connectors:File";
		SPCategories::catMap[0x1c41516] = "SharePoint Server Search|Connectors:HTTP";
		SPCategories::catMap[0x1c41516] = "SharePoint Foundation Search|Connectors:HTTP";
		SPCategories::catMap[0x1c41517] = "SharePoint Server Search|Connectors:People";
		SPCategories::catMap[0x1c41517] = "SharePoint Foundation Search|Connectors:People";
		SPCategories::catMap[0x1c41518] = "SharePoint Foundation Search|Connectors:Notes";
		SPCategories::catMap[0x1c41518] = "SharePoint Server Search|Connectors:Notes";
		SPCategories::catMap[0x1c41519] = "SharePoint Server Search|Connectors:Exchange";
		SPCategories::catMap[0x1c41519] = "SharePoint Foundation Search|Connectors:Exchange";
		SPCategories::catMap[0x1c4151a] = "SharePoint Foundation Search|Connectors:SharePoint";
		SPCategories::catMap[0x1c4151a] = "SharePoint Server Search|Connectors:SharePoint";
		SPCategories::catMap[0x1c4151b] = "SharePoint Server Search|Connectors:Framework";
		SPCategories::catMap[0x1c4151b] = "SharePoint Foundation Search|Connectors:Framework";
		SPCategories::catMap[0x252b014] = "Business Connectivity Services|Business Data";
		SPCategories::catMap[0x278e001] = "Excel Services Application|Excel Web Services";
		SPCategories::catMap[0x278e002] = "Excel Services Application|Excel Calculation Services";
		SPCategories::catMap[0x278e003] = "Excel Services Application|External Data";
		SPCategories::catMap[0x278e004] = "Excel Services Application|Cache";
		SPCategories::catMap[0x278e005] = "Excel Services Application|Session";
		SPCategories::catMap[0x278e006] = "Excel Services Application|Browser";
		SPCategories::catMap[0x278e007] = "Excel Services Application|Administration";
		SPCategories::catMap[0x278e008] = "Excel Services Application|Web Front End";
		SPCategories::catMap[0x278e009] = "Excel Services Application|Excel Mobile Viewer";
		SPCategories::catMap[0x278e00a] = "Excel Services Application|Data Model";
		SPCategories::catMap[0x38bb001] = "Visio Graphics Service|Administration";
		SPCategories::catMap[0x38bb002] = "Visio Graphics Service|Data Connection";
		SPCategories::catMap[0x38bb003] = "Visio Graphics Service|File Handler";
		SPCategories::catMap[0x38bb005] = "Visio Graphics Service|Refresh";
		SPCategories::catMap[0x38bb007] = "Visio Graphics Service|Graphics Service";
		SPCategories::catMap[0x38bb008] = "Visio Graphics Service|Web Access";
		SPCategories::catMap[0x38bb009] = "Visio Graphics Service|Rendering diagram model";
		SPCategories::catMap[0x38bb00a] = "Visio Graphics Service|Server object model";
		SPCategories::catMap[0x38bb00b] = "Visio Graphics Service|Recalculation";
		SPCategories::catMap[0x38bb00c] = "Visio Graphics Service|Parser";
		SPCategories::catMap[0x4468001] = "Project Server|Unified Logging Service";
		SPCategories::catMap[0x4468001] = "SharePoint Server|Unified Logging Service";
		SPCategories::catMap[0x4468001] = "SharePoint Foundation|Unified Logging Service";
		SPCategories::catMap[0x4468001] = "Search|Unified Logging Service";
		SPCategories::catMap[0x4468002] = "SharePoint Foundation|Logging Correlation Data";
		SPCategories::catMap[0x4468002] = "Search|Logging Correlation Data";
		SPCategories::catMap[0x4468002] = "SharePoint Server|Logging Correlation Data";
		SPCategories::catMap[0x4468002] = "Project Server|Logging Correlation Data";
		SPCategories::catMap[0x4468003] = "Project Server|SQM";
		SPCategories::catMap[0x4468003] = "SharePoint Server|SQM";
		SPCategories::catMap[0x4468003] = "Search|SQM";
		SPCategories::catMap[0x4468003] = "SharePoint Foundation|SQM";
		SPCategories::catMap[0x4468004] = "SharePoint Foundation|Micro Trace";
		SPCategories::catMap[0x4468004] = "SharePoint Server|Micro Trace";
		SPCategories::catMap[0x4468004] = "Search|Micro Trace";
		SPCategories::catMap[0x4468004] = "Project Server|Micro Trace";
		SPCategories::catMap[0x4468005] = "SharePoint Foundation|Tracing Controller Service";
		SPCategories::catMap[0x4cb0002] = "Access Services 2010|Data Layer";
		SPCategories::catMap[0x4cb0003] = "Access Services 2010|Application Publishing";
		SPCategories::catMap[0x4cb0004] = "Access Services 2010|Macro Processor";
		SPCategories::catMap[0x4cb0005] = "Access Services 2010|Query Processor";
		SPCategories::catMap[0x4cb0006] = "Access Services 2010|User Interface";
		SPCategories::catMap[0x4cb0007] = "Access Services 2010|Administration";
		SPCategories::catMap[0x4cb0008] = "Access Services 2010|Unknown";
		SPCategories::catMap[0x4cb0009] = "Access Services 2010|Web Front End";
		SPCategories::catMap[0x4cb000a] = "Access Services 2010|Expression Service";
		SPCategories::catMap[0x4cb000b] = "Access Services 2010|Application Design";
		SPCategories::catMap[0x4cb000c] = "Access Services 2010|Database Connection Management";
		SPCategories::catMap[0x4f33001] = "Services Infrastructure|Services Infrastructure Logging";
		SPCategories::catMap[0x4f33001] = "Office Services Infrastructure|Services Infrastructure Logging";
		SPCategories::catMap[0x4f33002] = "Office Services Infrastructure|Services Infrastructure Assert";
		SPCategories::catMap[0x4f33002] = "Services Infrastructure|Services Infrastructure Assert";
		SPCategories::catMap[0x4f33003] = "Services Infrastructure|Configuration";
		SPCategories::catMap[0x4f33003] = "Office Services Infrastructure|Configuration";
		SPCategories::catMap[0x4f33004] = "Office Services Infrastructure|Office Service Finder";
		SPCategories::catMap[0x4f33004] = "Services Infrastructure|Office Service Finder";
		SPCategories::catMap[0x4f33005] = "Office Services Infrastructure|Services Infrastructure Health";
		SPCategories::catMap[0x4f33005] = "Services Infrastructure|Services Infrastructure Health";
		SPCategories::catMap[0x4f33006] = "Office Services Infrastructure|Office Performance Tracing";
		SPCategories::catMap[0x4f33006] = "Services Infrastructure|Office Performance Tracing";
		SPCategories::catMap[0x4f33007] = "Office Services Infrastructure|Globalization";
		SPCategories::catMap[0x4f33007] = "Services Infrastructure|Globalization";
		SPCategories::catMap[0x4f33008] = "Office Services Infrastructure|Unrepresented Portable Log Cats";
		SPCategories::catMap[0x4f33008] = "Services Infrastructure|Unrepresented Portable Log Cats";
		SPCategories::catMap[0x4f33009] = "Services Infrastructure|Identity";
		SPCategories::catMap[0x4f33009] = "Office Services Infrastructure|Identity";
		SPCategories::catMap[0x5311001] = "Access Services|Test Layer";
		SPCategories::catMap[0x5311002] = "Access Services|Data Layer";
		SPCategories::catMap[0x5311003] = "Access Services|Application Publishing";
		SPCategories::catMap[0x5311004] = "Access Services|Macro Processor";
		SPCategories::catMap[0x5311005] = "Access Services|Query Processor";
		SPCategories::catMap[0x5311006] = "Access Services|User Interface";
		SPCategories::catMap[0x5311007] = "Access Services|Administration";
		SPCategories::catMap[0x5311008] = "Access Services|Unknown";
		SPCategories::catMap[0x5311009] = "Access Services|Web Front End";
		SPCategories::catMap[0x531100a] = "Access Services|Expression Service";
		SPCategories::catMap[0x531100b] = "Access Services|Application Design";
		SPCategories::catMap[0x531100c] = "Access Services|Database Connection Management";
		SPCategories::catMap[0x531100d] = "Access Services|Host Layer";
		SPCategories::catMap[0x531100e] = "Access Services|External Data";
		SPCategories::catMap[0x531100f] = "Access Services|Data Pipeline";
		SPCategories::catMap[0x6aa8001] = "Search|General";
		SPCategories::catMap[0x6aa8002] = "Search|Search Component";
		SPCategories::catMap[0x6aa8003] = "Search|Search HostController";
		SPCategories::catMap[0x6aa8004] = "Search|FsPlugin query tasks";
		SPCategories::catMap[0x6aa8005] = "Search|FsPlugin indexing tasks";
		SPCategories::catMap[0x6aa8006] = "Search|SP query tasks";
		SPCategories::catMap[0x6aa8007] = "Search|SP indexing related tasks";
		SPCategories::catMap[0x6aa8008] = "Search|Document Feeder";
		SPCategories::catMap[0x6aa8009] = "Search|Analysis Engine";
		SPCategories::catMap[0x6aa800a] = "Search|Search Analytics";
		SPCategories::catMap[0x6aa800b] = "Search|Query Processing";
		SPCategories::catMap[0x6aa800c] = "Search|Schema Service Consumer";
		SPCategories::catMap[0x6aa800d] = "Search|Index Lookup";
		SPCategories::catMap[0x6aa800e] = "Search|Category for tracing the NLG Extractors";
		SPCategories::catMap[0x6aa800f] = "Search|Linguistic Processing";
		SPCategories::catMap[0x6aa8010] = "Search|Usage Analytics";
		SPCategories::catMap[0x6aa8011] = "Search|Search Platform Services";
		SPCategories::catMap[0x6aa8012] = "Search|FastServer log";
		SPCategories::catMap[0x6aa8013] = "Search|Search Reports";
		SPCategories::catMap[0x6aa8014] = "Search|Document Parsing";
		SPCategories::catMap[0x6aa8015] = "Search|Search Backup & Restore";
		SPCategories::catMap[0x6aa8016] = "Search|Content Processing";
		SPCategories::catMap[0x6aa8017] = "Search|Common Processing";
		SPCategories::catMap[0x6aa8018] = "Search|Search Topology";
		SPCategories::catMap[0x6aa8019] = "Search|Alias Lookup Service";
		SPCategories::catMap[0x6aa801a] = "Search|Fuzzy Name Search";
		SPCategories::catMap[0x6aa801b] = "Search|Kvs query tasks";
		SPCategories::catMap[0x6aa801c] = "Search|Kvs indexing tasks";
		SPCategories::catMap[0x6aa801d] = "Search|Kvs general tasks";
		SPCategories::catMap[0x6aa801e] = "Search|Graph query tasks";
		SPCategories::catMap[0x6aa801f] = "Search|Graph indexing tasks";
		SPCategories::catMap[0x6aa8020] = "Search|Graph general tasks";
		SPCategories::catMap[0x6aa8021] = "Search|Key value store log";
		SPCategories::catMap[0x6aa8022] = "Search|Graph log";
		SPCategories::catMap[0x6aa8023] = "Search|Data Loss Prevention";
		SPCategories::catMap[0x6aa8024] = "Search|Exchange";
		SPCategories::catMap[0x6d54001] = "Search|Tracing Controller Service";
		SPCategories::catMap[0x6fb1002] = "Document Conversions|Launcher Service";
		SPCategories::catMap[0x6fb1003] = "Document Conversions|Load Balancer Service";
		SPCategories::catMap[0x6fb1004] = "Document Conversions|SharePoint Foundation";
		SPCategories::catMap[0x6fb7001] = "SharePoint Foundation|Backup and Restore";
		SPCategories::catMap[0x6fb7002] = "SharePoint Foundation|Configuration";
		SPCategories::catMap[0x6fb7003] = "SharePoint Foundation|Database";
		SPCategories::catMap[0x6fb7004] = "SharePoint Foundation|E-Mail";
		SPCategories::catMap[0x6fb7005] = "SharePoint Foundation|Feature Infrastructure";
		SPCategories::catMap[0x6fb7006] = "SharePoint Foundation|Fields";
		SPCategories::catMap[0x6fb7007] = "SharePoint Foundation|General";
		SPCategories::catMap[0x6fb7008] = "SharePoint Foundation|Health";
		SPCategories::catMap[0x6fb7009] = "SharePoint Foundation|Information Rights Management";
		SPCategories::catMap[0x6fb700a] = "SharePoint Foundation|Runtime";
		SPCategories::catMap[0x6fb700b] = "SharePoint Foundation|Server Help";
		SPCategories::catMap[0x6fb700c] = "SharePoint Foundation|Timer";
		SPCategories::catMap[0x6fb700d] = "SharePoint Foundation|Topology";
		SPCategories::catMap[0x6fb700e] = "SharePoint Foundation|Upgrade";
		SPCategories::catMap[0x6fb700f] = "SharePoint Foundation|Web Controls";
		SPCategories::catMap[0x6fb7010] = "SharePoint Foundation|Web Parts";
		SPCategories::catMap[0x6fb7011] = "SharePoint Foundation|Legacy Workflow Infrastructure";
		SPCategories::catMap[0x6fb7012] = "SharePoint Foundation|Http Throttling";
		SPCategories::catMap[0x6fb7013] = "SharePoint Foundation|Usage Infrastructure";
		SPCategories::catMap[0x6fb7014] = "SharePoint Foundation|Business Data";
		SPCategories::catMap[0x6fb7015] = "SharePoint Foundation|PowerShell";
		SPCategories::catMap[0x6fb7016] = "SharePoint Foundation|Site Subscription";
		SPCategories::catMap[0x6fb7017] = "SharePoint Foundation|Doc Conversion Communication";
		SPCategories::catMap[0x6fb7018] = "SharePoint Foundation|Doc Conversion Timer Job";
		SPCategories::catMap[0x6fb7019] = "SharePoint Foundation|Expression Service";
		SPCategories::catMap[0x6fb701a] = "SharePoint Foundation|Data Source Control";
		SPCategories::catMap[0x6fb7023] = "SharePoint Foundation|Database Extensions";
		SPCategories::catMap[0x6fb7026] = "SharePoint Foundation|Sandboxed Code Service";
		SPCategories::catMap[0x6fb702b] = "SharePoint Foundation|Lookup Relationships";
		SPCategories::catMap[0x6fb702c] = "SharePoint Foundation|List Uniqueness";
		SPCategories::catMap[0x6fb702d] = "SharePoint Foundation|App Deployment";
		SPCategories::catMap[0x6fb702e] = "SharePoint Foundation|Object Cache";
		SPCategories::catMap[0x6fb702f] = "SharePoint Foundation|Claims Authentication";
		SPCategories::catMap[0x6fb7030] = "SharePoint Foundation|Monitoring";
		SPCategories::catMap[0x6fb7031] = "SharePoint Foundation|Performance";
		SPCategories::catMap[0x6fb7032] = "SharePoint Foundation|Client File Access";
		SPCategories::catMap[0x6fb7033] = "SharePoint Foundation|SPRequest";
		SPCategories::catMap[0x6fb7034] = "SharePoint Foundation|Content Migration";
		SPCategories::catMap[0x6fb7035] = "SharePoint Foundation|Stack Trace Collection";
		SPCategories::catMap[0x6fb7036] = "SharePoint Foundation|Alerts";
		SPCategories::catMap[0x6fb7037] = "SharePoint Foundation|Template Cache";
		SPCategories::catMap[0x6fb7038] = "SharePoint Foundation|Browser SQM";
		SPCategories::catMap[0x6fb7039] = "SharePoint Foundation|Service Connections";
		SPCategories::catMap[0x6fb703a] = "SharePoint Foundation|Office Parser";
		SPCategories::catMap[0x6fb703b] = "SharePoint Foundation|DistributedCache";
		SPCategories::catMap[0x6fb703c] = "SharePoint Foundation|Request Management";
		SPCategories::catMap[0x6fb703d] = "SharePoint Foundation|App Management";
		SPCategories::catMap[0x6fb703e] = "SharePoint Foundation|App Marketplace";
		SPCategories::catMap[0x6fb703f] = "SharePoint Foundation|Cobalt";
		SPCategories::catMap[0x6fb7040] = "SharePoint Foundation|Workflow Services";
		SPCategories::catMap[0x6fb7041] = "SharePoint Foundation|Application Authentication";
		SPCategories::catMap[0x6fb7042] = "SharePoint Foundation|Azure Access Control";
		SPCategories::catMap[0x6fb7043] = "SharePoint Foundation|Files";
		SPCategories::catMap[0x6fb7044] = "SharePoint Foundation|Authentication Authorization";
		SPCategories::catMap[0x6fb7045] = "SharePoint Foundation|User Settings Provider";
		SPCategories::catMap[0x6fb7046] = "SharePoint Foundation|Security";
		SPCategories::catMap[0x6fb7047] = "SharePoint Foundation|Auditing";
		SPCategories::catMap[0x6fb7048] = "SharePoint Foundation|Send To External Repository";
		SPCategories::catMap[0x6fb7049] = "SharePoint Foundation|Network Usage";
		SPCategories::catMap[0x6fb704a] = "SharePoint Foundation|WOPI";
		SPCategories::catMap[0x6fb704b] = "SharePoint Foundation|BEC Web Service";
		SPCategories::catMap[0x6fb704c] = "SharePoint Foundation|Related Items";
		SPCategories::catMap[0x6fb704d] = "SharePoint Foundation|Document Sharing";
		SPCategories::catMap[0x6fb704e] = "SharePoint Foundation|CSOM";
		SPCategories::catMap[0x6fb704f] = "SharePoint Foundation|CSOM Api";
		SPCategories::catMap[0x6fb7050] = "SharePoint Foundation|RESTful List Data";
		SPCategories::catMap[0x6fb7051] = "SharePoint Foundation|Document Move";
		SPCategories::catMap[0x6fb7052] = "SharePoint Foundation|Marketplace Web Service";
		SPCategories::catMap[0x6fb7053] = "SharePoint Foundation|Dev Events";
		SPCategories::catMap[0x6fb7054] = "SharePoint Foundation|App Site Contexts";
		SPCategories::catMap[0x6fb7055] = "SharePoint Foundation|App Hosting Quota Management";
		SPCategories::catMap[0x6fb7056] = "SharePoint Foundation|App Monitoring";
		SPCategories::catMap[0x6fb7057] = "SharePoint Foundation|Site Collection Administrator Audit";
		SPCategories::catMap[0x6fb7058] = "SharePoint Foundation|Solution Exporter";
		SPCategories::catMap[0x6fb7059] = "SharePoint Foundation|App Auth";
		SPCategories::catMap[0x6fb705a] = "SharePoint Foundation|Asp Runtime";
		SPCategories::catMap[0x6fb705b] = "SharePoint Foundation|Online App Principal";
		SPCategories::catMap[0x6fb705c] = "SharePoint Foundation|TWS API";
		SPCategories::catMap[0x6fb705d] = "SharePoint Foundation|Flighting Infrastructure";
		SPCategories::catMap[0x6fb705e] = "SharePoint Foundation|SkySync REST Service";
		SPCategories::catMap[0x6fb705f] = "SharePoint Foundation|Audit Optics";
		SPCategories::catMap[0x6fb7060] = "SharePoint Foundation|Migration";
		SPCategories::catMap[0x6fb7061] = "SharePoint Foundation|Abs";
		SPCategories::catMap[0x6fb7062] = "SharePoint Foundation|Mount Point";
		SPCategories::catMap[0x6fb7063] = "SharePoint Foundation|Search";
		SPCategories::catMap[0x6fb7064] = "SharePoint Foundation|Resolve";
		SPCategories::catMap[0x6fb7066] = "SharePoint Foundation|User Key";
		SPCategories::catMap[0x6fb7067] = "SharePoint Foundation|Site Master";
		SPCategories::catMap[0x6fb7068] = "SharePoint Foundation|Site Cache";
		SPCategories::catMap[0x6fb7069] = "SharePoint Foundation|Site Map";
		SPCategories::catMap[0x6fb706a] = "SharePoint Foundation|Unified Audit";
		SPCategories::catMap[0x6fb706b] = "SharePoint Foundation|Config Cache";
		SPCategories::catMap[0x6fb706c] = "SharePoint Foundation|Config DB";
		SPCategories::catMap[0x6fb706d] = "SharePoint Foundation|SharePoint Insights";
		SPCategories::catMap[0x6fb706e] = "SharePoint Foundation|Static Configuration";
		SPCategories::catMap[0x6fb706f] = "SharePoint Foundation|Network Telemetry";
		SPCategories::catMap[0x6fb7070] = "SharePoint Foundation|SharePoint Federated Directory API";
		SPCategories::catMap[0x6fb7071] = "SharePoint Foundation|Audience Validation";
		SPCategories::catMap[0x6fb7072] = "SharePoint Foundation|Kill Switch";
		SPCategories::catMap[0x6fb7073] = "SharePoint Foundation|Cloud DNS";
		SPCategories::catMap[0x6fb7074] = "SharePoint Foundation|Compliance Settings";
		SPCategories::catMap[0x6fb7075] = "SharePoint Foundation|Micro Services";
		SPCategories::catMap[0x6fb7076] = "SharePoint Foundation|Security Token Service";
		SPCategories::catMap[0x6fb7077] = "SharePoint Foundation|Policy Enforcement";
		SPCategories::catMap[0x6fb7078] = "SharePoint Foundation|Dynamic Claims";
		SPCategories::catMap[0x6fb7079] = "SharePoint Foundation|TenantRouting";
		SPCategories::catMap[0x6fb707a] = "SharePoint Foundation|Public and Private CDN";
		SPCategories::catMap[0x6fb707b] = "SharePoint Foundation|This is for ABS Pre Drain feature";
		SPCategories::catMap[0x6fb707c] = "SharePoint Foundation|Security Token";
		SPCategories::catMap[0x6fb707d] = "SharePoint Foundation|Tenant Admin";
		SPCategories::catMap[0x6fb707e] = "SharePoint Foundation|MultiGeo";
		SPCategories::catMap[0x6fb707f] = "SharePoint Foundation|Security Token Handler";
		SPCategories::catMap[0x6fb7080] = "SharePoint Foundation|Security Token Service Caller";
		SPCategories::catMap[0x7354001] = "Secure Store Service|Secure Store";
		SPCategories::catMap[0x8b3d001] = "SharePoint Portal Server|Administration";
		SPCategories::catMap[0x8b3d002] = "SharePoint Portal Server|Backward Compatible Administration";
		SPCategories::catMap[0x8b3d003] = "SharePoint Portal Server|Backward Compatible Site Object Model";
		SPCategories::catMap[0x8b3d004] = "SharePoint Portal Server|Business Data";
		SPCategories::catMap[0x8b3d005] = "SharePoint Portal Server|Runtime";
		SPCategories::catMap[0x8b3d007] = "SharePoint Portal Server|Site Directory";
		SPCategories::catMap[0x8b3d008] = "SharePoint Portal Server|User Profiles";
		SPCategories::catMap[0x8b3d009] = "SharePoint Portal Server|Web Parts";
		SPCategories::catMap[0x8b3d00b] = "SharePoint Portal Server|Abstract Entity Instance";
		SPCategories::catMap[0x8b3d00d] = "SharePoint Portal Server|Application Registry";
		SPCategories::catMap[0x8b3d00e] = "SharePoint Portal Server|Links Checker Job Command Line";
		SPCategories::catMap[0x8b3d015] = "SharePoint Portal Server|Safe Event Log";
		SPCategories::catMap[0x8b3d016] = "SharePoint Portal Server|Long Running Operation";
		SPCategories::catMap[0x8b3d01c] = "SharePoint Portal Server|Personal Sites";
		SPCategories::catMap[0x8b3d01d] = "SharePoint Portal Server|Business Data Field";
		SPCategories::catMap[0x8b3d01e] = "SharePoint Portal Server|Business Data Field Control";
		SPCategories::catMap[0x8b3d01f] = "SharePoint Portal Server|Business Data Synchronizer Job";
		SPCategories::catMap[0x8b3d021] = "SharePoint Portal Server|Category Detail";
		SPCategories::catMap[0x8b3d022] = "SharePoint Portal Server|Excel Profile Page";
		SPCategories::catMap[0x8b3d024] = "SharePoint Portal Server|Scorecard Filter Toolpart";
		SPCategories::catMap[0x8b3d025] = "SharePoint Portal Server|User Context Filter Toolpart";
		SPCategories::catMap[0x8b3d026] = "SharePoint Portal Server|Group Detail Webpart";
		SPCategories::catMap[0x8b3d027] = "SharePoint Portal Server|Members Webpart";
		SPCategories::catMap[0x8b3d028] = "SharePoint Portal Server|Related Groups Webpart";
		SPCategories::catMap[0x8b3d029] = "SharePoint Portal Server|Cacheable Webpart";
		SPCategories::catMap[0x8b3d02a] = "SharePoint Portal Server|Site Directory Util";
		SPCategories::catMap[0x8b3d02b] = "SharePoint Portal Server|My Personal Space";
		SPCategories::catMap[0x8b3d02d] = "SharePoint Portal Server|Portal API";
		SPCategories::catMap[0x8b3d02e] = "SharePoint Portal Server|Quick Links";
		SPCategories::catMap[0x8b3d02f] = "SharePoint Portal Server|Webpart";
		SPCategories::catMap[0x8b3d030] = "SharePoint Portal Server|Search Boxes";
		SPCategories::catMap[0x8b3d031] = "SharePoint Portal Server|Category Webpart Toolbar";
		SPCategories::catMap[0x8b3d032] = "SharePoint Portal Server|Personal Pages";
		SPCategories::catMap[0x8b3d034] = "SharePoint Portal Server|Webpart Page";
		SPCategories::catMap[0x8b3d035] = "SharePoint Portal Server|Tasks and Tools";
		SPCategories::catMap[0x8b3d036] = "SharePoint Portal Server|Profile Image Picker";
		SPCategories::catMap[0x8b3d037] = "SharePoint Portal Server|Profile Property Loader";
		SPCategories::catMap[0x8b3d038] = "SharePoint Portal Server|Site Upgrade Utils";
		SPCategories::catMap[0x8b3d039] = "SharePoint Portal Server|Item Picker";
		SPCategories::catMap[0x8b3d03a] = "SharePoint Portal Server|Soap Server Exception";
		SPCategories::catMap[0x8b3d03b] = "SharePoint Portal Server|SPS Crawl";
		SPCategories::catMap[0x8b3d03c] = "SharePoint Portal Server|Toolbar";
		SPCategories::catMap[0x8b3d03d] = "SharePoint Portal Server|SPS People";
		SPCategories::catMap[0x8b3d03f] = "SharePoint Portal Server|Claims Authentication";
		SPCategories::catMap[0x8b3d040] = "SharePoint Portal Server|SPS Exchange Notifications";
		SPCategories::catMap[0x8b3d041] = "SharePoint Portal Server|Communities";
		SPCategories::catMap[0x8b3d043] = "SharePoint Portal Server|Project Discovery";
		SPCategories::catMap[0x8b3d044] = "SharePoint Portal Server|Site Mailbox";
		SPCategories::catMap[0x8b3d045] = "SharePoint Portal Server|Microfeeds";
		SPCategories::catMap[0x8b3d046] = "SharePoint Portal Server|My Site Document Library";
		SPCategories::catMap[0x8b3d048] = "SharePoint Portal Server|Personal Site Instantiation";
		SPCategories::catMap[0x8b3d049] = "SharePoint Portal Server|Feed Cache";
		SPCategories::catMap[0x8b3d04a] = "SharePoint Portal Server|Personal Site Upgrade";
		SPCategories::catMap[0x8b3d04b] = "SharePoint Portal Server|Content Following";
		SPCategories::catMap[0x8b3d04c] = "SharePoint Portal Server|Exchange Task Synchronization";
		SPCategories::catMap[0x8b3d04d] = "SharePoint Portal Server|Work Management Service";
		SPCategories::catMap[0x8b3d04e] = "SharePoint Portal Server|Work Management Data Model";
		SPCategories::catMap[0x8b3d04f] = "SharePoint Portal Server|My Tasks Dashboard";
		SPCategories::catMap[0x8b3d050] = "SharePoint Portal Server|Announcement Tiles";
		SPCategories::catMap[0x8b3d051] = "SharePoint Portal Server|Group";
		SPCategories::catMap[0x8b3d052] = "SharePoint Portal Server|My Projects";
		SPCategories::catMap[0x8b3d053] = "SharePoint Portal Server|PointPublishing";
		SPCategories::catMap[0x8b3d054] = "SharePoint Portal Server|PublicCdn";
		SPCategories::catMap[0x8b3d055] = "SharePoint Portal Server|PersonalCache";
		SPCategories::catMap[0xa349001] = "InfoPath Forms Services|Administration";
		SPCategories::catMap[0xa349002] = "InfoPath Forms Services|Conversion and Deployment";
		SPCategories::catMap[0xa349003] = "InfoPath Forms Services|Runtime";
		SPCategories::catMap[0xa349004] = "InfoPath Forms Services|Runtime - Business Logic";
		SPCategories::catMap[0xa349005] = "InfoPath Forms Services|Runtime - Data Connections";
		SPCategories::catMap[0xa349006] = "InfoPath Forms Services|Runtime - State Service";
		SPCategories::catMap[0xa34900f] = "InfoPath Forms Services|Maintenance";
		SPCategories::catMap[0xa7cd001] = "PerformancePoint Service|PerformancePoint Services";
		SPCategories::catMap[0xb217001] = "Project Server|Active Cache operations";
		SPCategories::catMap[0xb217002] = "Project Server|Active Cache Resource Load";
		SPCategories::catMap[0xb217003] = "Project Server|Active Cache Load";
		SPCategories::catMap[0xb217004] = "Project Server|Active Cache Save";
		SPCategories::catMap[0xb217005] = "Project Server|Active Directory Sync";
		SPCategories::catMap[0xb217006] = "Project Server|Drivers and Prioritizations";
		SPCategories::catMap[0xb217007] = "Project Server|Portfolio Strategy Optimizer";
		SPCategories::catMap[0xb217008] = "Project Server|Portfolio Strategy Planner";
		SPCategories::catMap[0xb217009] = "Project Server|Archive, Restore";
		SPCategories::catMap[0xb21700a] = "Project Server|Calendars";
		SPCategories::catMap[0xb21700b] = "Project Server|Analysis Cube Building";
		SPCategories::catMap[0xb21700c] = "Project Server|Global";
		SPCategories::catMap[0xb21700d] = "Project Server|Notifications";
		SPCategories::catMap[0xb21700e] = "Project Server|Server-side Project Operations";
		SPCategories::catMap[0xb217010] = "Project Server|Reporting";
		SPCategories::catMap[0xb217011] = "Project Server|Resource";
		SPCategories::catMap[0xb217012] = "Project Server|Security";
		SPCategories::catMap[0xb217013] = "Project Server|General";
		SPCategories::catMap[0xb217014] = "Project Server|Provisioning";
		SPCategories::catMap[0xb217015] = "Project Server|Queue";
		SPCategories::catMap[0xb217016] = "Project Server|Server-Side Events";
		SPCategories::catMap[0xb217017] = "Project Server|Sharepoint Integration";
		SPCategories::catMap[0xb217018] = "Project Server|Task Statusing and Updates";
		SPCategories::catMap[0xb217019] = "Project Server|Status Reports";
		SPCategories::catMap[0xb21701a] = "Project Server|Summary Resource Assignments";
		SPCategories::catMap[0xb21701b] = "Project Server|Timesheet";
		SPCategories::catMap[0xb21701c] = "Project Server|Project Web App";
		SPCategories::catMap[0xb21701d] = "Project Server|Project Server Workflow";
		SPCategories::catMap[0xb21701e] = "Project Server|Exchange Sync";
		SPCategories::catMap[0xb21701f] = "Project Server|Server BI";
		SPCategories::catMap[0xb217020] = "Project Server|Administration";
		SPCategories::catMap[0xb217021] = "Project Server|Project Server Cache";
		SPCategories::catMap[0xb217022] = "Project Server|Project Server Shared";
		SPCategories::catMap[0xb217023] = "Project Server|Database";
		SPCategories::catMap[0xb217024] = "Project Server|Shared Services";
		SPCategories::catMap[0xb217025] = "Project Server|Project Server OData";
		SPCategories::catMap[0xb217026] = "Project Server|Project Calculation Service (M)";
		SPCategories::catMap[0xb217027] = "Project Server|Work Management";
		SPCategories::catMap[0xb217028] = "Project Server|Project Server Database";
		SPCategories::catMap[0xb217029] = "Project Server|Project Server SQL Batch";
		SPCategories::catMap[0xb21702a] = "Project Server|Project Server Timeline";
		SPCategories::catMap[0xb21702b] = "Project Server|InProcess Service Host";
		SPCategories::catMap[0xb21702c] = "Project Server|Project Server Upgrade";
		SPCategories::catMap[0xb21702d] = "Project Server|Project Calculation Service (N)";
		SPCategories::catMap[0xb21702e] = "Project Server|Queue Jobs";
		SPCategories::catMap[0xb21702f] = "Project Server|Backend Communication";
		SPCategories::catMap[0xb217030] = "Project Server|Analytics Logs";
		SPCategories::catMap[0xb217031] = "Project Server|Engagements";
		SPCategories::catMap[0xb949001] = "Education|Data Access Layer";
		SPCategories::catMap[0xb949002] = "Education|Data Aggregation";
		SPCategories::catMap[0xb949004] = "Education|Lync Integration";
		SPCategories::catMap[0xb949005] = "Education|Exchange Integration";
		SPCategories::catMap[0xb949006] = "Education|Notifications";
		SPCategories::catMap[0xb949007] = "Education|Provisioning";
		SPCategories::catMap[0xb949008] = "Education|Unified Data Warehouse";
		SPCategories::catMap[0xb949009] = "Education|Academic Library";
		SPCategories::catMap[0xb94900a] = "Education|Quiz";
		SPCategories::catMap[0xb94900b] = "Education|Administration";
		SPCategories::catMap[0xb94900c] = "Education|Presentation Layer";
		SPCategories::catMap[0xb94900d] = "Education|Change Puller";
		SPCategories::catMap[0xc33b001] = "SharePoint Server|General";
		SPCategories::catMap[0xc33b002] = "SharePoint Server|Setup and Upgrade";
		SPCategories::catMap[0xc33b003] = "SharePoint Server|Shared Services";
		SPCategories::catMap[0xc33b004] = "SharePoint Server|Taxonomy";
		SPCategories::catMap[0xc33b005] = "SharePoint Server|OpenXml";
		SPCategories::catMap[0xc33b006] = "SharePoint Server|Feature Push Down Manager";
		SPCategories::catMap[0xc33b007] = "SharePoint Server|Service Timer Job Handler";
		SPCategories::catMap[0xc33b008] = "SharePoint Server|Setup Licensing";
		SPCategories::catMap[0xc33b00a] = "SharePoint Server|Audit";
		SPCategories::catMap[0xc33b00b] = "SharePoint Server|Command Base";
		SPCategories::catMap[0xc33b00c] = "SharePoint Server|Comand Base Validators";
		SPCategories::catMap[0xc33b00e] = "SharePoint Server|Event Throttle";
		SPCategories::catMap[0xc33b00f] = "SharePoint Server|Http Encoding Utility";
		SPCategories::catMap[0xc33b013] = "SharePoint Server|Prepare to Move";
		SPCategories::catMap[0xc33b014] = "SharePoint Server|Sync Commands";
		SPCategories::catMap[0xc33b016] = "SharePoint Server|User Profile";
		SPCategories::catMap[0xc33b017] = "SharePoint Server|User Profile Manager";
		SPCategories::catMap[0xc33b018] = "SharePoint Server|Session State Service";
		SPCategories::catMap[0xc33b019] = "SharePoint Server|Social Data";
		SPCategories::catMap[0xc33b01a] = "SharePoint Server|Database";
		SPCategories::catMap[0xc33b01b] = "SharePoint Server|Topology";
		SPCategories::catMap[0xc33b01c] = "SharePoint Server|State Service";
		SPCategories::catMap[0xc33b01d] = "SharePoint Server|SP Cache";
		SPCategories::catMap[0xc33b01e] = "SharePoint Server|SP Cache Config";
		SPCategories::catMap[0xc33b01f] = "SharePoint Server|Workflow Services";
		SPCategories::catMap[0xc33b020] = "SharePoint Server|Distributed Cache";
		SPCategories::catMap[0xc33b021] = "SharePoint Server|Federated Directory Core";
		SPCategories::catMap[0xc33b022] = "SharePoint Server|Federated Directory Adapter";
		SPCategories::catMap[0xc33b023] = "SharePoint Server|My Site Provisioning";
		SPCategories::catMap[0xc33b024] = "SharePoint Server|Site Provisioning";
		SPCategories::catMap[0xc33b025] = "SharePoint Server|User Profile Monitor";
		SPCategories::catMap[0xc544001] = "Word Automation Services|General";
		SPCategories::catMap[0xc544002] = "Word Automation Services|Timer Job";
		SPCategories::catMap[0xc544003] = "Word Automation Services|Object Model";
		SPCategories::catMap[0xc544004] = "Word Automation Services|Service";
		SPCategories::catMap[0xc544005] = "Word Automation Services|Configuration";
		SPCategories::catMap[0xc544006] = "Word Automation Services|Database";
		SPCategories::catMap[0xc544007] = "Word Automation Services|Backup and Restore";
		SPCategories::catMap[0xc544008] = "Word Automation Services|PowerShell";
		SPCategories::catMap[0xc544009] = "Word Automation Services|Administration";
		SPCategories::catMap[0xc54400a] = "Word Automation Services|Synchronous Conversion";
		SPCategories::catMap[0xc8a9001] = "SharePoint Translation Services|General";
		SPCategories::catMap[0xc8a9002] = "SharePoint Translation Services|Timer Job";
		SPCategories::catMap[0xc8a9003] = "SharePoint Translation Services|Object Model";
		SPCategories::catMap[0xc8a9004] = "SharePoint Translation Services|Service";
		SPCategories::catMap[0xc8a9005] = "SharePoint Translation Services|Configuration";
		SPCategories::catMap[0xc8a9006] = "SharePoint Translation Services|Database";
		SPCategories::catMap[0xc8a9007] = "SharePoint Translation Services|Backup and Restore";
		SPCategories::catMap[0xc8a9008] = "SharePoint Translation Services|PowerShell";
		SPCategories::catMap[0xc8a9009] = "SharePoint Translation Services|Administration";
		SPCategories::catMap[0xc8a900a] = "SharePoint Translation Services|Document Parsing";
		SPCategories::catMap[0xc8a900b] = "SharePoint Translation Services|Machine Translation";
		SPCategories::catMap[0xc8a900c] = "SharePoint Translation Services|Synchronous Job";
		SPCategories::catMap[0xc8a900d] = "SharePoint Translation Services|Translation";
		SPCategories::catMap[0xd191001] = "SharePoint Express|Generic";
		SPCategories::catMap[0xd191002] = "SharePoint Express|Site Library";
		SPCategories::catMap[0xe0e6002] = "eApproval|Enhanced Group Management Pages";
		SPCategories::catMap[0xe0e6003] = "eApproval|Library";
		SPCategories::catMap[0xe0e6005] = "eApproval|Schedules";
		SPCategories::catMap[0xe0e6006] = "eApproval|SOAP";
		SPCategories::catMap[0xf78d001] = "Document Management Server|Document Management";
		SPCategories::catMap[0xf78d002] = "Document Management Server|Records Center";
		SPCategories::catMap[0xf78d003] = "Document Management Server|Information Policy Management";
		SPCategories::catMap[0xf78d004] = "Document Management Server|Workflow Features";
		SPCategories::catMap[0xf78d005] = "Document Management Server|Reporting";
		SPCategories::catMap[0xf78d006] = "Document Management Server|Document Sets";
		SPCategories::catMap[0xf78d007] = "Document Management Server|Content Organizer";
		SPCategories::catMap[0xf78d008] = "Document Management Server|Document Conversions";
		SPCategories::catMap[0xf78d009] = "Document Management Server|Holds";
		SPCategories::catMap[0xf78d00a] = "Document Management Server|Discovery";
		SPCategories::catMap[0xf78d00b] = "Document Management Server|Information Rights Management";
		SPCategories::catMap[0xf78d00c] = "Document Management Server|IPAED Usage Optics";
		SPCategories::catMap[0xf78d00d] = "Document Management Server|IPAED Perf Optics";
		SPCategories::catMap[0xf78d00e] = "Document Management Server|IPAED Error Optics";
		SPCategories::catMap[0xf78d00f] = "Document Management Server|Unified Policy";
		SPCategories::catMap[0xf78d010] = "Document Management Server|Unified Dlp Policy Application";
		SPCategories::catMap[0xf78d011] = "Document Management Server|Task Generator";
		SPCategories::catMap[0x84468002] = "Unified Logging Service|Logging Correlation Data";
		SPCategories::catMap[0xffffffff] = "SharePoint Server|Unknown";
		SPCategories::catMap[0xffffffff] = "Project Server|Unknown";
		SPCategories::catMap[0xffffffff] = "SharePoint Foundation|Unknown";
	}
}


